In [4]:
import seaborn as sns

In [6]:
import seaborn as sns
sns.get_dataset_names()
df = sns.load_dataset("mpg")
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [7]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [8]:
df.shape

(398, 9)

In [16]:
df.shape[1]

9

In [17]:
# variableların pythonda hangi veri tipine karşılık geldiğini gösterir
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [18]:
df.info

<bound method DataFrame.info of       mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu

In [10]:
df.select_dtypes(include=["object"])

origin                       name
0       usa  chevrolet chevelle malibu
1       usa          buick skylark 320
2       usa         plymouth satellite
3       usa              amc rebel sst
4       usa                ford torino
..      ...                        ...
393     usa            ford mustang gl
394  europe                  vw pickup
395     usa              dodge rampage
396     usa                ford ranger
397     usa                 chevy s-10

[398 rows x 2 columns]

In [11]:
df.select_dtypes(exclude=["object"])

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

In [13]:
# unique miktarları
df.nunique(axis=0)

mpg             129
cylinders         5
displacement     82
horsepower       93
weight          351
acceleration     95
model_year       13
origin            3
name            305
dtype: int64

In [15]:
df.plot.pie(y=[135, 120,23])

KeyError: "None of [Int64Index([135, 120, 23], dtype='int64')] are in the [columns]"

In [19]:
df.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.491160   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   93.500000  2803.500000   
75%     29.000000    8.000000    262.000000  126.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model_year  
count    398.000000  398.000000  
mean      15.568090   76.010050  
std        2.757689    3.697627  
min        8.000000   70.000000  
25%       13.825000   73.000000  
50%       15.500000   76.000000  
75%       17.175000   79.000000  
max       24.800000   82.000000

In [20]:
# popülasyon üretme
# herkesin aynı sayı üretmesini sağlar
import numpy as np

In [23]:
np.random.seed(101)
population = np.random.randint(0,100, size=1000000)

In [24]:
population

array([95, 11, 81, ...,  7, 96, 13])

In [25]:
len(population)

1000000

In [28]:
np.random.seed(101)
sample = np.random.choice(population, 100)

In [29]:
sample

array([69, 30, 10, 18, 36, 24, 92, 40, 72,  6, 26, 40, 30, 13, 50, 88, 52,
       59, 83, 97, 67, 11,  8, 89,  2, 87, 81, 58, 89, 67, 60, 18, 60, 61,
       75, 98, 47, 42, 35, 13, 38, 31, 91, 30, 91, 64, 86,  4, 92,  7,  8,
       40, 70, 47, 50,  4, 20, 73, 61, 88, 89, 43,  1,  3, 71, 85, 91, 28,
       45, 47, 81, 27, 71, 16, 40, 47, 93, 68, 50, 92, 87, 74, 30, 92, 80,
       71, 34, 79, 76, 37, 41, 27, 77, 71, 66, 22, 91, 96, 40, 10])

In [31]:
np.random.seed(51)
sample = np.random.choice(population, 100)

In [32]:
sample

array([57, 79, 63, 45, 58, 10, 66, 67, 81, 41, 46, 44, 35, 53, 20, 35, 51,
       76, 90, 46, 49, 49, 79, 65,  9, 65, 42, 45, 98, 44, 50, 18, 80, 84,
       74, 78, 89, 89, 87, 21, 29,  5, 80, 24, 49, 45, 55,  4, 97, 26, 35,
       14, 30, 96, 20, 91, 81, 36, 70, 57, 86, 18, 77, 42, 49, 89, 29, 96,
       29, 97,  8, 77, 52, 37, 28, 16, 74, 70, 62, 40, 92, 96, 44, 89, 59,
       69,  4, 58, 23, 82, 42, 50, 74,  0,  2, 19, 55, 79, 56, 27])

In [33]:
population.mean()

49.512218

In [34]:
sample.mean()

53.18

In [38]:
sample_means = []

for i in range(100):
   sample = np.random.choice(population, 100)
   sample_means.append(sample.mean())

sample_means

[47.74,
 50.89,
 49.95,
 48.52,
 52.13,
 50.08,
 49.14,
 46.75,
 49.83,
 52.45,
 50.13,
 52.58,
 49.84,
 47.08,
 49.03,
 51.25,
 53.42,
 51.42,
 49.13,
 45.1,
 47.3,
 47.23,
 53.92,
 47.82,
 52.24,
 44.99,
 52.32,
 54.5,
 48.78,
 51.54,
 45.51,
 52.48,
 47.17,
 50.7,
 45.53,
 48.23,
 50.52,
 49.56,
 52.63,
 52.05,
 47.97,
 43.73,
 52.27,
 51.75,
 52.67,
 45.14,
 47.32,
 50.23,
 48.1,
 51.82,
 52.25,
 49.63,
 47.45,
 49.1,
 50.69,
 50.61,
 45.96,
 47.18,
 48.2,
 49.0,
 49.64,
 49.75,
 47.83,
 50.94,
 48.91,
 47.97,
 46.53,
 47.15,
 50.32,
 47.86,
 48.89,
 50.81,
 55.79,
 52.2,
 47.67,
 50.91,
 53.79,
 50.15,
 48.54,
 49.23,
 51.93,
 54.13,
 52.38,
 49.28,
 53.21,
 48.5,
 53.54,
 46.43,
 49.96,
 53.5,
 49.39,
 51.31,
 51.78,
 52.19,
 51.11,
 49.04,
 49.19,
 53.25,
 47.48,
 46.43]

In [1]:
np.mean(sample_means)

NameError: name 'np' is not defined