In [64]:
import numpy as np
import time
import sys

In [65]:
l = range(1000)
print(sys.getsizeof(5) * len(l))

28000


In [66]:
array = np.arange(1000) # create arrange 0 to 999
print(array.size*array.itemsize)

4000


In [67]:
# WHY NUMPYIS FAST THAN LIST
SIZE = 1000000
l1 = range(SIZE)
l2 = range(SIZE)
a1 = np.arange(SIZE)
a2 =np.arange(SIZE)
# Python lists 
start = time.time()
result = {(x+y) for x, y in zip(l1, l2)}
print("python list took: ", (time.time()-start)*1000)

# numpy array
start = time.time()
result = a1 + a2
print("numpy array took: ", (time.time()-start)*1000)


python list took:  423.96068572998047
numpy array took:  31.9974422454834


In [68]:
A1 = np.array([1,2,3])
A2 = np.array([4,5,6])
A1+A2


array([5, 7, 9])

In [69]:
A1-A2

array([-3, -3, -3])

In [70]:
A1*A2

array([ 4, 10, 18])

In [71]:
A1/A2

array([0.25, 0.4 , 0.5 ])

ARRAY OPERATIONS

In [72]:
import numpy as np

In [73]:
a = np.array([5,6,9])
a[0]

5

In [74]:
a[1]

6

In [75]:
a = np.array([[1,2], [3,4], [5,6]])
a.ndim

2

In [76]:
a=np.array([5,6,9])
a.ndim

1

In [77]:
a=np.array([5,6,9])
a.ndim

1

In [78]:
a.itemsize

4

In [79]:
a.dtype

dtype('int32')

In [80]:
a=np.array([[1,2], [3,4], [5,6]], dtype=np.float64)
a.itemsize

8

In [81]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [82]:
a.size

6

In [83]:
a.shape

(3, 2)

In [84]:
a=np.array([[1,2], [3,4], [5,6]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [85]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [87]:
l=range(5)
l

range(0, 5)

In [88]:
l[0]

0

In [89]:
l[1]

1

In [90]:
np.arange(1,5)

array([1, 2, 3, 4])

In [91]:
np.arange(1,5,2)

array([1, 3])

In [92]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [93]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [94]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [95]:
a.shape

(3, 2)

In [96]:
a.reshape(2,3)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [97]:
a.ravel()

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [98]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [99]:
a.min()

(1+0j)

In [100]:
a.max()

(6+0j)

In [101]:
a = np.array([[1,2], [3,4], [5,6]])

In [102]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [103]:
a.min()

1

In [104]:
a.max()

6

In [105]:
a.sum()

21

In [106]:
a.sum(axis=0)

array([ 9, 12])

In [107]:
a.sum(axis=1)

array([ 3,  7, 11])

In [108]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [109]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [110]:
np.std(a)

1.707825127659933

In [111]:
a =np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [112]:
b= np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [113]:
a+b

array([[ 6,  8],
       [10, 12]])

In [114]:
a.dot(b)  # matrix product

array([[19, 22],
       [43, 50]])

1. INDEXING, SLICING
2. ITERATING THROUGH ARRAYS
3. STACKING TOGETHER TWO ARRAYS
4. INDEXING WITH BOOLEAN ARRAYS


In [1]:
import numpy as np

In [2]:
n= [6,7,8,]
n

[6, 7, 8]

In [3]:
n[0:2]

[6, 7]

In [4]:
n[-1]

8

In [6]:
a =np.array([6,7,8,])
a[0:2]

array([6, 7])

In [7]:
a[-1]

8

In [9]:
a = np.array([[6,7,8,], [1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [10]:
#anlamadım
a[1,2]

3

In [11]:
# ANLAMADIM
a[0:2,2]

array([8, 3])

In [12]:
a[-1]

array([9, 3, 2])

In [14]:
a[-1, 0:2]

array([9, 3])

In [15]:
# ANLAMADIM
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [16]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [17]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [19]:
import numpy as np

In [22]:
c = np.arange(6).reshape(3,2)
d = np.arange(6,12).reshape(3,2)

In [23]:
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
d

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
np.vstack((c,d))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [26]:
np.hstack((c, d))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [27]:
e = np.arange(30).reshape(2,15)

In [28]:
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [29]:
np.hsplit(e,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [31]:
result = np.hsplit(e, 3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [32]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [33]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [35]:
result = np.vsplit(e, 2)
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [36]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
f = np.arange(12).reshape(3,4)
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
g =f>4
g

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
f[g]

array([ 5,  6,  7,  8,  9, 10, 11])

In [43]:
f[g]= -1
f

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])