In [1]:
import numpy as np
np.__version__

'1.20.3'

In [2]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [3]:
type(my_list)

list

In [5]:
a1 = np.array([[1,2,3,4],[1,2,3,4],[2,3,4,5]])
b1 = np.array([[2,3,4,5],[1,2,4,5],[1,2,3,4]])

In [6]:
a1.size

12

In [7]:
a1.shape

(3, 4)

In [8]:
a1.itemsize

4

In [9]:
a1+b1

array([[3, 5, 7, 9],
       [2, 4, 7, 9],
       [3, 5, 7, 9]])

In [10]:
a1*b1

array([[ 2,  6, 12, 20],
       [ 1,  4, 12, 20],
       [ 2,  6, 12, 20]])

In [11]:
a3 = np.array([[[1,2,3,4],[1,2,3,4],[2,3,4,5]], [[1,2,3,4],[1,2,3,4],[2,3,4,5]]])
a3

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [2, 3, 4, 5]]])

In [ ]:
np.arange()

In [15]:
arr = np.array([1, 2, True])
arr

array([1, 2, 1])

In [4]:
import matplotlib.pyplot as plt
%matplotlib inline

ModuleNotFoundError: No module named 'matplotlib'

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [10]:
import  matplotlib.pyplot as plt
%matplotlib inline

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
c = np.zeros_like(a)
c

array([0, 0, 0])

In [14]:
c.dtype

dtype('int32')

In [15]:
c.shape

(3,)

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones_like(a)

array([1, 1, 1])

In [19]:
np.empty(3)

array([1., 1., 1.])

In [20]:
np.empty_like(a)

array([1653645632,        658,          0])

In [22]:
np.full(4, 7)

array([7, 7, 7, 7])

In [24]:
np.full_like(a,7)

array([7, 7, 7])

In [25]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [26]:
np.arange(4.)

array([0., 1., 2., 3.])