The Basics

In [3]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int32'

In [7]:
a.itemsize

4

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([6, 7, 8])

In [11]:
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

Array Creation

In [1]:
import numpy as np
>>> a = np.array([2, 3, 4])
>>> a

array([2, 3, 4])

In [2]:
>>> b = np.array([(1.5, 2, 3), (4, 5, 6)])
>>> b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])