In [3]:
import numpy as np
import time
import sys

In [2]:
l = range(1000)
print(sys.getsizeof(5) * len(l))

28000


In [4]:
array = np.arange(1000) # create arrange 0 to 999
print(array.size*array.itemsize)

4000


In [7]:
# WHY NUMPYIS FAST THAN LIST
SIZE = 1000000
l1 = range(SIZE)
l2 = range(SIZE)
a1 = np.arange(SIZE)
a2 =np.arange(SIZE)
# Python lists 
start = time.time()
result = {(x+y) for x, y in zip(l1, l2)}
print("python list took: ", (time.time()-start)*1000)

# numpy array
start = time.time()
result = a1 + a2
print("numpy array took: ", (time.time()-start)*1000)


python list took:  507.1895122528076
numpy array took:  64.96334075927734


In [9]:
A1 = np.array([1,2,3])
A2 = np.array([4,5,6])
A1+A2


array([-3, -3, -3])

In [10]:
A1-A2

array([-3, -3, -3])

In [11]:
A1*A2

array([ 4, 10, 18])

In [12]:
A1/A2

array([0.25, 0.4 , 0.5 ])

ARRAY OPERATIONS

In [14]:
import numpy as np

In [15]:
a = np.array([5,6,9])
a[0]

5

In [16]:
a[1]

6

In [18]:
a = np.array([[1,2], [3,4], [5,6]])
a.ndim

2

In [19]:
a=np.array([5,6,9])
a.ndim

1

In [21]:
a=np.array([5,6,9])
a.ndim

1

In [22]:
a.itemsize

4

In [23]:
a.dtype

dtype('int32')

In [24]:
a=np.array([[1,2], [3,4], [5,6]], dtype=np.float64)
a.itemsize

8

In [25]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [26]:
a.size

6

In [27]:
a.shape

(3, 2)

In [28]:
a=np.array([[1,2], [3,4], [5,6]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
l=range(5)
l

range(0, 5)

In [33]:
l[0]

0

In [34]:
l[1]

1

In [35]:
np.arange(1,5)

array([1, 2, 3, 4])

In [36]:
np.arange(1,5,2)

array([1, 3])

In [37]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [38]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [39]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [40]:
a.shape

(3, 2)

In [41]:
a.reshape(2,3)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [42]:
a.ravel()

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [43]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [44]:
a.min()

(1+0j)

In [45]:
a.max()

(6+0j)

In [47]:
a = np.array([[1,2], [3,4], [5,6]])

In [48]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
a.min()

1

In [50]:
a.max()

6

In [51]:
a.sum()

21

In [52]:
a.sum(axis=0)

array([ 9, 12])

In [53]:
a.sum(axis=1)

array([ 3,  7, 11])

In [54]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [55]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
np.std(a)

1.707825127659933

In [57]:
a =np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [59]:
b= np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [60]:
a+b

array([[ 6,  8],
       [10, 12]])

In [61]:
a.dot(b)  # matrix product

array([[19, 22],
       [43, 50]])

1. INDEXING, SLICING
2. ITERATING THROUGH ARRAYS
3. STACKING TOGETHER TWO ARRAYS
4. INDEXING WITH BOOLEAN ARRAYS
