In [1]:
import numpy as np
import time
import sys

In [290]:
l = range(1000)
print(sys.getsizeof(5) * len(l))

28000


In [291]:
array = np.arange(1000) # create arrange 0 to 999
print(array.size*array.itemsize)

4000


In [292]:
# WHY NUMPYIS FAST THAN LIST
SIZE = 1000000
l1 = range(SIZE)
l2 = range(SIZE)
a1 = np.arange(SIZE)
a2 =np.arange(SIZE)
# Python lists 
start = time.time()
result = {(x+y) for x, y in zip(l1, l2)}
print("python list took: ", (time.time()-start)*1000)

# numpy array
start = time.time()
result = a1 + a2
print("numpy array took: ", (time.time()-start)*1000)


python list took:  676.6119003295898
numpy array took:  40.97414016723633


In [293]:
A1 = np.array([1,2,3])
A2 = np.array([4,5,6])
A1+A2


array([5, 7, 9])

In [294]:
A1-A2

array([-3, -3, -3])

In [295]:
A1*A2

array([ 4, 10, 18])

In [296]:
A1/A2

array([0.25, 0.4 , 0.5 ])

ARRAY OPERATIONS

In [297]:
import numpy as np

In [298]:
a = np.array([5,6,9])
a[0]

5

In [299]:
a[1]

6

In [300]:
a = np.array([[1,2], [3,4], [5,6]])
a.ndim

2

In [301]:
a=np.array([5,6,9])
a.ndim

1

In [302]:
a=np.array([5,6,9])
a.ndim

1

In [303]:
a.itemsize

4

In [304]:
a.dtype

dtype('int32')

In [305]:
a=np.array([[1,2], [3,4], [5,6]], dtype=np.float64)
a.itemsize

8

In [306]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [307]:
a.size

6

In [308]:
a.shape

(3, 2)

In [309]:
a=np.array([[1,2], [3,4], [5,6]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [310]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [311]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [312]:
l=range(5)
l

range(0, 5)

In [313]:
l[0]

0

In [314]:
l[1]

1

In [315]:
np.arange(1,5)

array([1, 2, 3, 4])

In [316]:
np.arange(1,5,2)

array([1, 3])

In [317]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [318]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [319]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [320]:
a.shape

(3, 2)

In [321]:
a.reshape(2,3)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [322]:
a.ravel()

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [323]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [324]:
a.min()

(1+0j)

In [325]:
a.max()

(6+0j)

In [326]:
a = np.array([1,2], [3,4], [5,6])
a

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
a = np.array([[1,2], [3,4], [5,6]])

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.min()

1

In [ ]:
a.max()

6

In [ ]:
a.sum()

21

In [ ]:
a.sum(axis=0)

array([ 9, 12])

In [ ]:
a.sum(axis=1)

array([ 3,  7, 11])

In [ ]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.std(a)

1.707825127659933

In [ ]:
a =np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b= np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a.dot(b)  # matrix product

array([[19, 22],
       [43, 50]])

1. INDEXING, SLICING
2. ITERATING THROUGH ARRAYS
3. STACKING TOGETHER TWO ARRAYS
4. INDEXING WITH BOOLEAN ARRAYS


In [ ]:
import numpy as np

In [ ]:
n= [6,7,8,]
n

[6, 7, 8]

In [ ]:
n[0:2]

[6, 7]

In [ ]:
n[-1]

8

In [ ]:
a =np.array([6,7,8,])
a[0:2]

array([6, 7])

In [ ]:
a[-1]

8

In [ ]:
a = np.array([[6,7,8,], [1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [ ]:
#anladım
a[1,2]

3

In [ ]:
# ANLADIM
a[0:2,2]

array([8, 3])

In [ ]:
a[-1]

array([9, 3, 2])

In [ ]:
a[-1, 0:2]

array([9, 3])

In [ ]:
# ANLADIM
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [ ]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [ ]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [ ]:
import numpy as np

In [ ]:
c = np.arange(6).reshape(3,2)
d = np.arange(6,12).reshape(3,2)

In [ ]:
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
d

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((c,d))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.hstack((c, d))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [ ]:
e = np.arange(30).reshape(2,15)

In [ ]:
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
np.hsplit(e,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [ ]:
np.hsplit(e,5)

[array([[ 0,  1,  2],
        [15, 16, 17]]),
 array([[ 3,  4,  5],
        [18, 19, 20]]),
 array([[ 6,  7,  8],
        [21, 22, 23]]),
 array([[ 9, 10, 11],
        [24, 25, 26]]),
 array([[12, 13, 14],
        [27, 28, 29]])]

In [ ]:
result = np.hsplit(e, 3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [ ]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [ ]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [ ]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [ ]:
result = np.vsplit(e, 2)
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [ ]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
f = np.arange(12).reshape(3,4)
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
g =f>4
g

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
f[g]

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
f[g]= -1
f

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [ ]:
import numpy as np

THE BASICS

In [ ]:
ı = np.array([1,2,3,], dtype='int16')
print(ı)

[1 2 3]


In [ ]:
i = np.array([[9.0, 8.0,7.0],[6.0, 5.0, 4.0]])
i

array([[9., 8., 7.],
       [6., 5., 4.]])

In [ ]:
# get dimension
ı.ndim

1

In [ ]:
# get shape
i.shape

(2, 3)

In [ ]:
# get Type
ı.dtype

dtype('int16')

In [ ]:
# Get Size
ı.itemsize

2

In [ ]:
# get total size
ı.nbytes

6

In [ ]:
# GEt Shape
i.shape

(2, 3)

ASSESCING/CHANGING SPESIFIC ELEMENTS, ROWS, COLUMNS, ETC

In [ ]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
# gET a spesific element(r, c)
a[1,5]

13

In [ ]:
# gET aa spesific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a spesific column
a[:, 2]

array([ 3, 10])

In [ ]:
# Getting {startindex:endindex:stepsize}
a[0, 1:-1:2]

array([2, 4, 6])

In [ ]:
a[1,5]=20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [ ]:
a[1,5] =20
a[:,2] =[1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

3D example

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
#replace
b[:,1,:]= [[9,9],[8,8,]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

INITIALIZING DIFFERENT TYPES OF ARRAYS

In [ ]:
#All Os Matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [ ]:
# All 1s Matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [ ]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
#Any other number number (full_like)
np.full_like(a.shape, 4)

array([4, 4])

In [ ]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#Random Decimal Numbers
np.random.rand(4,2,3)

array([[[0.1347533 , 0.77056065, 0.19347506],
        [0.88330695, 0.40086497, 0.10307577]],

       [[0.64703392, 0.47338485, 0.58454817],
        [0.70187728, 0.93592968, 0.64037287]],

       [[0.62694602, 0.64559369, 0.63426924],
        [0.05684847, 0.14803407, 0.41247698]],

       [[0.04800369, 0.7116707 , 0.83519559],
        [0.8215726 , 0.7118275 , 0.33282354]]])

In [ ]:
np.random.random_sample(a.shape)

array([[0.08173089, 0.4881537 , 0.00299851, 0.9659546 , 0.80098778,
        0.8084781 , 0.15377222],
       [0.40649747, 0.08395982, 0.23168436, 0.08137751, 0.68238069,
        0.64783629, 0.94366532]])

In [ ]:
np.random.rand(4,2)

array([[0.36228269, 0.50847134],
       [0.29296107, 0.87656057],
       [0.94872307, 0.28826197],
       [0.66976585, 0.80976128]])

In [ ]:
#Random İnteger Values
np.random.randint(7)

3

In [ ]:
np.random.randint(7, size=(3,3))

array([[1, 2, 1],
       [6, 6, 4],
       [3, 4, 3]])

In [ ]:
np.random.randint(4,7, size=(3,3))

array([[5, 5, 5],
       [6, 5, 5],
       [4, 4, 6]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
31.46.dakka

AttributeError: 'float' object has no attribute 'dakka'

In [ ]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#%matplotlib inline

In [ ]:
np.random.seed(42)
df3 = pd.DataFrame(  np.random.randn(5,4),
                   index = ['A', 'B', 'C', 'D', 'E'],
                   columns = 'W X Y Z'.split()          )
df3

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [ ]:
df6 = pd.DataFrame({'groups': ['A', 'B', 'C', 'A', 'B', 'C','A', 'B', 'C'],
                   'var1': [10,23,33,22,11,99,40,20,15],
                   'var2': [100,253,333,262,111,969, 232,343,123]})
df6

groups  var1  var2
0      A    10   100
1      B    23   253
2      C    33   333
3      A    22   262
4      B    11   111
5      C    99   969
6      A    40   232
7      B    20   343
8      C    15   123

In [ ]:
df6[["var1", "var2"]].transform(lambda x: (x- df6["var1"].min())/(df6[["var1"]].max()-df6[["var1"]].min()))

ValueError: Function did not transform

In [ ]:
df6[["var1"]].transform(lambda x : ( x - df6["var1"].min() )/
                                       (df6["var1"].max()-df6["var1"].min())
                       )




var1
0  0.000000
1  0.146067
2  0.258427
3  0.134831
4  0.011236
5  1.000000
6  0.337079
7  0.112360
8  0.056180

In [ ]:
df6[["var1","var2"]].transform(lambda x: (x - df6["var1"].min())/(
                                              df6["var1"].max()-df6["var1"].min()))

var1       var2
0  0.000000   1.011236
1  0.146067   2.730337
2  0.258427   3.629213
3  0.134831   2.831461
4  0.011236   1.134831
5  1.000000  10.775281
6  0.337079   2.494382
7  0.112360   3.741573
8  0.056180   1.269663

In [ ]:

df6[['var1']].transform(lambda x : (x - x.min()) / (x.max() - x.min()))

var1
0  0.000000
1  0.146067
2  0.258427
3  0.134831
4  0.011236
5  1.000000
6  0.337079
7  0.112360
8  0.056180

In [ ]:
df6[["var1","var2"]].apply(lambda x : ( x - df6["var1"].min() )/
                                       (df6["var1"].max()-df6["var1"].min())  )  # make minmaxscaler

var1       var2
0  0.000000   1.011236
1  0.146067   2.730337
2  0.258427   3.629213
3  0.134831   2.831461
4  0.011236   1.134831
5  1.000000  10.775281
6  0.337079   2.494382
7  0.112360   3.741573
8  0.056180   1.269663

In [ ]:
df6[["var1","var2"]].apply( lambda x : ( x - df6[["var1","var2"]].min() )/
                                       (df6[["var1","var2"]].max()-df6[["var1","var2"]].min())
                       )

var1  var2
0      NaN   NaN
1      NaN   NaN
2      NaN   NaN
3      NaN   NaN
4      NaN   NaN
5      NaN   NaN
6      NaN   NaN
7      NaN   NaN
8      NaN   NaN
var1   NaN   NaN
var2   NaN   NaN

In [ ]:
df6.groupby('groups')[["var1", "var2"]].transform(np.mean)

var1        var2
0  24.0  198.000000
1  18.0  235.666667
2  49.0  475.000000
3  24.0  198.000000
4  18.0  235.666667
5  49.0  475.000000
6  24.0  198.000000
7  18.0  235.666667
8  49.0  475.000000

In [ ]:
df6.groupby('groups')[["var1", "var2"]].apply(np.mean)

var1        var2
groups                  
A       24.0  198.000000
B       18.0  235.666667
C       49.0  475.000000

In [ ]:
df6[["var1"]].transform([np.sqrt])

var1
       sqrt
0  3.162278
1  4.795832
2  5.744563
3  4.690416
4  3.316625
5  9.949874
6  6.324555
7  4.472136
8  3.872983

In [ ]:
df6.groupby("groups").filter(lambda x : x["var2"].mean() > 200).groupby("groups").mean()

var1        var2
groups                  
B       18.0  235.666667
C       49.0  475.000000

In [ ]:
titanic = sns.load_dataset('titanic')
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [ ]:
titanic.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
titanic.pivot_table(values="survived", index="sex", columns="pclass")

pclass         1         2         3
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
df = pd.DataFrame({'A':[1, 2, np.nan],
                  'B':[5, np.nan, np.nan],
                  'C':[1, 2, 3]})
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.isnull().sum()

A    1
B    2
C    0
dtype: int64

In [ ]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [ ]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [ ]:
df.dropna()

In [ ]:
df2 =df.append(pd.DataFrame([np.nan])).reset_index(drop=True)
df2

A    B    C   0
0  1.0  5.0  1.0 NaN
1  2.0  NaN  2.0 NaN
2  NaN  NaN  3.0 NaN
3  NaN  NaN  NaN NaN

In [ ]:
df2.dropna(how="all")

A    B    C   0
0  1.0  5.0  1.0 NaN
1  2.0  NaN  2.0 NaN
2  NaN  NaN  3.0 NaN

In [ ]:
df2.dropna(thresh=1, axis=0)
df2

A    B    C   0
0  1.0  5.0  1.0 NaN
1  2.0  NaN  2.0 NaN
2  NaN  NaN  3.0 NaN
3  NaN  NaN  NaN NaN

In [ ]:
df2.dropna(thresh=2, axis=0)
df2

A    B    C   0
0  1.0  5.0  1.0 NaN
1  2.0  NaN  2.0 NaN
2  NaN  NaN  3.0 NaN
3  NaN  NaN  NaN NaN

In [ ]:
df2.dropna(thresh=3, axis=0)
df2

A    B    C   0
0  1.0  5.0  1.0 NaN
1  2.0  NaN  2.0 NaN
2  NaN  NaN  3.0 NaN
3  NaN  NaN  NaN NaN