In [1]:
import numpy as np
import time
import sys

In [119]:
l = range(1000)
print(sys.getsizeof(5) * len(l))

28000


In [3]:
array = np.arange(1000) # create arrange 0 to 999
print(array.size*array.itemsize)

4000


In [4]:
# WHY NUMPYIS FAST THAN LIST
SIZE = 1000000
l1 = range(SIZE)
l2 = range(SIZE)
a1 = np.arange(SIZE)
a2 =np.arange(SIZE)
# Python lists 
start = time.time()
result = {(x+y) for x, y in zip(l1, l2)}
print("python list took: ", (time.time()-start)*1000)

# numpy array
start = time.time()
result = a1 + a2
print("numpy array took: ", (time.time()-start)*1000)


python list took:  593.8456058502197
numpy array took:  40.97580909729004


In [5]:
A1 = np.array([1,2,3])
A2 = np.array([4,5,6])
A1+A2


array([5, 7, 9])

In [6]:
A1-A2

array([-3, -3, -3])

In [7]:
A1*A2

array([ 4, 10, 18])

In [8]:
A1/A2

array([0.25, 0.4 , 0.5 ])

ARRAY OPERATIONS

In [9]:
import numpy as np

In [10]:
a = np.array([5,6,9])
a[0]

5

In [11]:
a[1]

6

In [12]:
a = np.array([[1,2], [3,4], [5,6]])
a.ndim

2

In [13]:
a=np.array([5,6,9])
a.ndim

1

In [14]:
a=np.array([5,6,9])
a.ndim

1

In [15]:
a.itemsize

4

In [16]:
a.dtype

dtype('int32')

In [17]:
a=np.array([[1,2], [3,4], [5,6]], dtype=np.float64)
a.itemsize

8

In [18]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [19]:
a.size

6

In [20]:
a.shape

(3, 2)

In [21]:
a=np.array([[1,2], [3,4], [5,6]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
l=range(5)
l

range(0, 5)

In [25]:
l[0]

0

In [26]:
l[1]

1

In [27]:
np.arange(1,5)

array([1, 2, 3, 4])

In [28]:
np.arange(1,5,2)

array([1, 3])

In [29]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [30]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [31]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [32]:
a.shape

(3, 2)

In [33]:
a.reshape(2,3)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [34]:
a.ravel()

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [35]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [36]:
a.min()

(1+0j)

In [37]:
a.max()

(6+0j)

In [120]:
a = np.array([1,2], [3,4], [5,6])
a

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [38]:
a = np.array([[1,2], [3,4], [5,6]])

In [39]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
a.min()

1

In [41]:
a.max()

6

In [42]:
a.sum()

21

In [43]:
a.sum(axis=0)

array([ 9, 12])

In [44]:
a.sum(axis=1)

array([ 3,  7, 11])

In [45]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [46]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
np.std(a)

1.707825127659933

In [48]:
a =np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [49]:
b= np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [50]:
a+b

array([[ 6,  8],
       [10, 12]])

In [51]:
a.dot(b)  # matrix product

array([[19, 22],
       [43, 50]])

1. INDEXING, SLICING
2. ITERATING THROUGH ARRAYS
3. STACKING TOGETHER TWO ARRAYS
4. INDEXING WITH BOOLEAN ARRAYS


In [52]:
import numpy as np

In [53]:
n= [6,7,8,]
n

[6, 7, 8]

In [54]:
n[0:2]

[6, 7]

In [55]:
n[-1]

8

In [56]:
a =np.array([6,7,8,])
a[0:2]

array([6, 7])

In [57]:
a[-1]

8

In [58]:
a = np.array([[6,7,8,], [1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [59]:
#anladım
a[1,2]

3

In [60]:
# ANLADIM
a[0:2,2]

array([8, 3])

In [61]:
a[-1]

array([9, 3, 2])

In [62]:
a[-1, 0:2]

array([9, 3])

In [63]:
# ANLADIM
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [64]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [65]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [66]:
import numpy as np

In [67]:
c = np.arange(6).reshape(3,2)
d = np.arange(6,12).reshape(3,2)

In [68]:
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [69]:
d

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [70]:
np.vstack((c,d))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [71]:
np.hstack((c, d))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [72]:
e = np.arange(30).reshape(2,15)

In [73]:
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [122]:
np.hsplit(e,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [121]:
np.hsplit(e,5)

[array([[ 0,  1,  2],
        [15, 16, 17]]),
 array([[ 3,  4,  5],
        [18, 19, 20]]),
 array([[ 6,  7,  8],
        [21, 22, 23]]),
 array([[ 9, 10, 11],
        [24, 25, 26]]),
 array([[12, 13, 14],
        [27, 28, 29]])]

In [125]:
result = np.hsplit(e, 3)
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [126]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [76]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [77]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [78]:
result = np.vsplit(e, 2)
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [79]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [80]:
f = np.arange(12).reshape(3,4)
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
g =f>4
g

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [82]:
f[g]

array([ 5,  6,  7,  8,  9, 10, 11])

In [83]:
f[g]= -1
f

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [84]:
import numpy as np

THE BASICS

In [85]:
ı = np.array([1,2,3,], dtype='int16')
print(ı)

[1 2 3]


In [86]:
i = np.array([[9.0, 8.0,7.0],[6.0, 5.0, 4.0]])
i

array([[9., 8., 7.],
       [6., 5., 4.]])

In [87]:
# get dimension
ı.ndim

1

In [88]:
# get shape
i.shape

(2, 3)

In [89]:
# get Type
ı.dtype

dtype('int16')

In [90]:
# Get Size
ı.itemsize

2

In [91]:
# get total size
ı.nbytes

6

In [92]:
# GEt Shape
i.shape

(2, 3)

ASSESCING/CHANGING SPESIFIC ELEMENTS, ROWS, COLUMNS, ETC

In [93]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [94]:
# gET a spesific element(r, c)
a[1,5]

13

In [95]:
# gET aa spesific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [96]:
# Get a spesific column
a[:, 2]

array([ 3, 10])

In [97]:
# Getting {startindex:endindex:stepsize}
a[0, 1:-1:2]

array([2, 4, 6])

In [98]:
a[1,5]=20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [99]:
a[1,5] =20
a[:,2] =[1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

3D example

In [100]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [101]:
#replace
b[:,1,:]= [[9,9],[8,8,]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

INITIALIZING DIFFERENT TYPES OF ARRAYS

In [102]:
#All Os Matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [103]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [104]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [105]:
# All 1s Matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [106]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [107]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [108]:
#Any other number number (full_like)
np.full_like(a.shape, 4)

array([4, 4])

In [109]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [110]:
#Random Decimal Numbers
np.random.rand(4,2,3)

array([[[0.1347533 , 0.77056065, 0.19347506],
        [0.88330695, 0.40086497, 0.10307577]],

       [[0.64703392, 0.47338485, 0.58454817],
        [0.70187728, 0.93592968, 0.64037287]],

       [[0.62694602, 0.64559369, 0.63426924],
        [0.05684847, 0.14803407, 0.41247698]],

       [[0.04800369, 0.7116707 , 0.83519559],
        [0.8215726 , 0.7118275 , 0.33282354]]])

In [111]:
np.random.random_sample(a.shape)

array([[0.08173089, 0.4881537 , 0.00299851, 0.9659546 , 0.80098778,
        0.8084781 , 0.15377222],
       [0.40649747, 0.08395982, 0.23168436, 0.08137751, 0.68238069,
        0.64783629, 0.94366532]])

In [112]:
np.random.rand(4,2)

array([[0.36228269, 0.50847134],
       [0.29296107, 0.87656057],
       [0.94872307, 0.28826197],
       [0.66976585, 0.80976128]])

In [113]:
#Random İnteger Values
np.random.randint(7)

3

In [114]:
np.random.randint(7, size=(3,3))

array([[1, 2, 1],
       [6, 6, 4],
       [3, 4, 3]])

In [115]:
np.random.randint(4,7, size=(3,3))

array([[5, 5, 5],
       [6, 5, 5],
       [4, 4, 6]])

In [116]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [117]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [118]:
31.46.dakka

AttributeError: 'float' object has no attribute 'dakka'