In [3]:
import numpy as np
np.empty((2,2,2))

array([[[1.77978809e+241, 3.30586060e+257],
        [2.28725472e-308, 3.38460762e+125]],

       [[7.20091312e+252, 1.33360328e+241],
        [4.31571504e-310, 3.92810296e-273]]])

In [4]:
np.random.rand()

array([[[0.33789919],
        [0.89204865]],

       [[0.61366493],
        [0.01623351]],

       [[0.96239427],
        [0.59136598]]])

In [5]:
np.random.randint(0,10,size=(5,5))

array([[7, 5, 8, 2, 6],
       [1, 5, 6, 4, 3],
       [7, 4, 9, 3, 9],
       [4, 0, 9, 3, 0],
       [0, 6, 6, 5, 1]])

Access all raws and all columns

In [9]:
a = np.random.randint(0,10,size=(5,5))
a[:,:]

array([[7, 0, 7, 3, 4],
       [6, 7, 8, 0, 1],
       [7, 9, 3, 3, 1],
       [7, 8, 4, 5, 9],
       [4, 8, 5, 0, 8]])

In [11]:
# particular row but all columns
a[[0,4,2],:]

array([[7, 0, 7, 3, 4],
       [4, 8, 5, 0, 8],
       [7, 9, 3, 3, 1]])

In [14]:
#all row but particular columns
a[:,1:4]

array([[0, 7, 3],
       [7, 8, 0],
       [9, 3, 3],
       [8, 4, 5],
       [8, 5, 0]])

In [10]:
# first row but all columns
a[0,:]

array([7, 0, 7, 3, 4])

In [7]:
np.linspace(1, 20, 15)

array([ 1.        ,  2.35714286,  3.71428571,  5.07142857,  6.42857143,
        7.78571429,  9.14285714, 10.5       , 11.85714286, 13.21428571,
       14.57142857, 15.92857143, 17.28571429, 18.64285714, 20.        ])