Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [3]:
import numpy as np
def checkerboard(n):
    return np.indices(n).sum(axis = 0) % 2
checkerboard((8,8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

In [7]:
arr = np.zeros((8,8), dtype=int)
arr [::2,1::2], arr[1::2, ::2] = 1,1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [10]:
a = np.arange(2,11).reshape(3,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

 Write a NumPy program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [23]:
b = np.arange(12,38)
b
np.flip(b)

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [2]:
import numpy as np

Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.

In [22]:
a = np.array(['clarusway','data', 'science', 'bootcamp', 'is', 'the', 'best'])
print(np.char.capitalize(a))
print(np.char.upper(a))
print(np.char.swapcase(a))
print(np.char.title(a))

['Clarusway' 'Data' 'Science' 'Bootcamp' 'Is' 'The' 'Best']
['CLARUSWAY' 'DATA' 'SCIENCE' 'BOOTCAMP' 'IS' 'THE' 'BEST']
['CLARUSWAY' 'DATA' 'SCIENCE' 'BOOTCAMP' 'IS' 'THE' 'BEST']
['Clarusway' 'Data' 'Science' 'Bootcamp' 'Is' 'The' 'Best']


In [10]:
np.char.upper(a)

array(['CLARUSWAY', 'DATA', 'SCIENCE', 'BOOTCAMP', 'IS', 'THE', 'BEST'],
      dtype='<U9')

In [16]:
b = np.array(['clarusway','data', 'science', 'bootcamp', 'is', 'the', 'best'])
b
np.char.swapcase(b)

array(['CLARUSWAY', 'DATA', 'SCIENCE', 'BOOTCAMP', 'IS', 'THE', 'BEST'],
      dtype='<U9')

In [18]:
b = np.array(['clarusway','data', 'science', 'bootcamp', 'is', 'the', 'best'])
b
np.char.title(b)

array(['Clarusway', 'Data', 'Science', 'Bootcamp', 'Is', 'The', 'Best'],
      dtype='<U9')