In [1]:
import numpy as np
np.__version__

'1.20.3'

In [2]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [3]:
type(my_list)

list

In [5]:
a1 = np.array([[1,2,3,4],[1,2,3,4],[2,3,4,5]])
b1 = np.array([[2,3,4,5],[1,2,4,5],[1,2,3,4]])

In [6]:
a1.size

12

In [7]:
a1.shape

(3, 4)

In [8]:
a1.itemsize

4

In [9]:
a1+b1

array([[3, 5, 7, 9],
       [2, 4, 7, 9],
       [3, 5, 7, 9]])

In [10]:
a1*b1

array([[ 2,  6, 12, 20],
       [ 1,  4, 12, 20],
       [ 2,  6, 12, 20]])

In [11]:
a3 = np.array([[[1,2,3,4],[1,2,3,4],[2,3,4,5]], [[1,2,3,4],[1,2,3,4],[2,3,4,5]]])
a3

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [2, 3, 4, 5]]])

In [ ]:
np.arange()

In [15]:
arr = np.array([1, 2, True])
arr

array([1, 2, 1])

In [20]:
import matplotlib.pyplot as plt
%matplotlib inline

ModuleNotFoundError: No module named 'matplotlib'