In [13]:
import numpy as np 
import pandas as pd 


In [ ]:
PANDS SERİSİ OLUŞTURMA

In [14]:
np.random.seed(42)
df3 = pd.DataFrame(  np.random.randn(5,4), 
                   index = ['A', 'B', 'C', 'D', 'E'], 
                   columns = 'W X Y Z'.split()          )
df3

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
serr= pd.Series([11,1223,34])
serr

0      11
1    1223
2      34
dtype: int64

In [6]:
data=["Ankara", "İstanbul", "İzmir"]
index=["A", "B", "C"]
pd.Series(data,index)

A      Ankara
B    İstanbul
C       İzmir
dtype: object

In [15]:
np.random.seed(42)
df=pd.DataFrame(np.random.randn(5,4)), index=["A","B","C","D","E"],
columns="K L M N"
df

SyntaxError: cannot assign to function call (Temp/ipykernel_11160/3157006195.py, line 2)

INDEX ADINI DEĞİŞTİRME

In [16]:
df3

W         X         Y         Z
A  0.496714 -0.138264  0.647689  1.523030
B -0.234153 -0.234137  1.579213  0.767435
C -0.469474  0.542560 -0.463418 -0.465730
D  0.241962 -1.913280 -1.724918 -0.562288
E -1.012831  0.314247 -0.908024 -1.412304

In [17]:
df3.index='a b c d e'.split()
df3

W         X         Y         Z
a  0.496714 -0.138264  0.647689  1.523030
b -0.234153 -0.234137  1.579213  0.767435
c -0.469474  0.542560 -0.463418 -0.465730
d  0.241962 -1.913280 -1.724918 -0.562288
e -1.012831  0.314247 -0.908024 -1.412304

Tablonun tüm değerlerini liste şeklinde görme

In [19]:
list(df3.items())

[('W',
  a    0.496714
  b   -0.234153
  c   -0.469474
  d    0.241962
  e   -1.012831
  Name: W, dtype: float64),
 ('X',
  a   -0.138264
  b   -0.234137
  c    0.542560
  d   -1.913280
  e    0.314247
  Name: X, dtype: float64),
 ('Y',
  a    0.647689
  b    1.579213
  c   -0.463418
  d   -1.724918
  e   -0.908024
  Name: Y, dtype: float64),
 ('Z',
  a    1.523030
  b    0.767435
  c   -0.465730
  d   -0.562288
  e   -1.412304
  Name: Z, dtype: float64)]

İndexi görme

In [20]:
df3.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

SÜTUN İSİMLERİNİ GÖRME

In [22]:
df3.keys()

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [53]:
# GARİP OLDU
df3["W":"X"]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

TABLONUN DEĞERLERİNİ GÖRME

In [23]:
df3.values

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [24]:
#values() ile göstermiyor.
df3.values()

TypeError: 'numpy.ndarray' object is not callable

TABLONUN DEĞERLERİNİ İNDİSE GÖRE GÖRME

In [25]:
#1.SATIRADKİ DEĞERELERİ GÖSTERİYOR.
df3.values[1]

array([-0.23415337, -0.23413696,  1.57921282,  0.76743473])

INDEXLERİ SIRALAMA

In [26]:
df3.sort_index()

W         X         Y         Z
a  0.496714 -0.138264  0.647689  1.523030
b -0.234153 -0.234137  1.579213  0.767435
c -0.469474  0.542560 -0.463418 -0.465730
d  0.241962 -1.913280 -1.724918 -0.562288
e -1.012831  0.314247 -0.908024 -1.412304

DEĞERELERİ SIRALAMA

In [38]:
df3.sort_values(by=df3)

KeyError:           W         X         Y         Z
a  0.496714 -0.138264  0.647689  1.523030
b -0.234153 -0.234137  1.579213  0.767435
c -0.469474  0.542560 -0.463418 -0.465730
d  0.241962 -1.913280 -1.724918 -0.562288
e -1.012831  0.314247 -0.908024 -1.412304

INDISE GÖRE DEĞERLERİ GÖRME

In [39]:
df3["W"]

a    0.496714
b   -0.234153
c   -0.469474
d    0.241962
e   -1.012831
Name: W, dtype: float64

In [41]:
df3["X"]

a   -0.138264
b   -0.234137
c    0.542560
d   -1.913280
e    0.314247
Name: X, dtype: float64

In [42]:
df3["Y"]

a    0.647689
b    1.579213
c   -0.463418
d   -1.724918
e   -0.908024
Name: Y, dtype: float64

In [43]:
df3.W

a    0.496714
b   -0.234153
c   -0.469474
d    0.241962
e   -1.012831
Name: W, dtype: float64

In [44]:
df3.X

a   -0.138264
b   -0.234137
c    0.542560
d   -1.913280
e    0.314247
Name: X, dtype: float64

In [47]:
df3[["W","X"]]

W         X
a  0.496714 -0.138264
b -0.234153 -0.234137
c -0.469474  0.542560
d  0.241962 -1.913280
e -1.012831  0.314247

In [54]:
df3[1:4]

W         X         Y         Z
b -0.234153 -0.234137  1.579213  0.767435
c -0.469474  0.542560 -0.463418 -0.465730
d  0.241962 -1.913280 -1.724918 -0.562288

DEĞERELERİN TABLODA OLUP OLMADIĞINI KNTROL ETME