1.Write a NumPy program to get the numpy version and show numpy build configuration.

In [4]:
import numpy as np
np.__version__
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3/envs/my-env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3/envs/my-env\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3/envs/my-env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3/envs/my-env\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3/envs/my-env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3/envs/my-env\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3/envs/my-env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Use

In [5]:
# Get help on the add function
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

Test whether none of the elements of a given array is zero

In [6]:
x = np.array([1, 2, 3, 4])
np.all(x)

True

In [7]:
x = np.array([0, 1, 2, 3])
np.all(x)

False

4. Write a NumPy program to test whether any of the elements of a given array is non-zero. 

In [8]:
x = np.array([1, 0, 0, 0])
np.any(x)

True

In [9]:
x = np.array([0, 0, 0, 0])
np.any(x)

False

5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number)

In [11]:
a = np.array([1, 0, np.nan, np.inf])
a
np.isfinite(a)

array([ True,  True, False, False])

6. Write a NumPy program to test element-wise for positive or negative infinity.

In [12]:
a = np.array([1, 0, np.nan, np.inf])
np.isinf(a)

array([False, False, False,  True])

7. Write a NumPy program to test element-wise for NaN of a given array.

In [13]:
a = np.array([1, 0, np.nan, np.inf])
np.isnan(a)

array([False, False,  True, False])

 Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [15]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
np.iscomplex(a)


array([False,  True,  True,  True,  True, False])

In [17]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
np.isreal(a)

array([False,  True,  True,  True,  True, False])

In [18]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print(np.isreal(a))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

[False  True  True  True  True False]
Checking for scalar type:
True
False


Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

Note: The tolerance values are positive, typically very small numbers. The relative difference (rtol * abs(b)) and the absolute difference atol are added together to compare against the absolute difference between a and b.

In [19]:
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


NumPy: Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [20]:
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [ ]:
Create an element-wise comparison (equal, equal within a tolerance) of two given arrays

In [21]:
import numpy as np
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("Original numbers:")
print(x)
print(y)
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Original numbers:
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:
True


Create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array

In [29]:
x = np.array([1,7,13,103])
print(x)
(x.size) * (x.itemsize)



[  1   7  13 103]


16

Create an array of 10 zeros, 10 ones, 10 fives

In [35]:
print(np.zeros(10))
print(np.ones(10))
print(np.ones(10)*5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Create an array of the integers from 30 to 70

In [39]:
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

Create a 3x3 identity matrix

In [41]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Generate a random number between 0 and 1

In [43]:
np.random.normal(0,1,1)

array([-0.02096555])

In [44]:
np.random.normal(0,1,3)

array([-0.45818692,  0.97360862,  0.72367297])

In [ ]:
Create a 3x3 identity matrix

Generate an array of 15 random numbers from a standard normal distribution

In [45]:
np.random.normal(0,1,15)

array([-0.25696203,  1.0463876 ,  0.44770744,  1.0804988 ,  1.38713475,
        0.00752607, -0.25677047, -0.04927738,  1.03030939,  0.54023469,
        0.03246347, -0.61522897, -2.74008752, -0.26162765,  1.10202074])

Create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last

In [46]:
np.arange(15+1, 55-1)

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

Create a 3X4 array using and iterate over it

In [52]:
np.arange(3,15).reshape(3,4)

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

Create a vector of length 10 with values ​​evenly distributed between 5 and 50

In [53]:
np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

Create a vector with values ​​from 0 to 20 and change the sign of the numbers in the range from 9 to 15

In [58]:
x= np.arange(0,21)
x[(x >= 9) & (x <= 15)] *= -1
x

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

Create a vector of length 5 filled with arbitrary integers from 0 to 10

In [65]:
np.random.randint(0,11, 5)

array([10, 10,  5,  3,  5])

Multiply the values ​​of two given vectors

In [69]:
x = np.array([1, 8, 3, 5])
print(x)
y= np.random.randint(0, 11, 4)
print(y)
x*y

[1 8 3 5]
[9 7 1 0]


array([ 9, 56,  3,  0])

Create a 3x4 matrix filled with values ​​from 10 to 21

In [73]:
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

Create an array of all the even integers from 30 to 70

In [76]:
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [77]:
x = np.array([x for x in range(30,71) if x %2 ==0])
print(x)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


27. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0